### ISSUE TITLE
Just want to test it on macOS

### ISSUE THREAD

**Issue by azoreseuropa** [adam-becker/psxact#19]
I love an accurate emulators like that. I compiled many other emulators for macOS thanks to their developers with help. 

I hope, you as the developer, to help me through it so people can read it and compile it for their macOS to enjoying your emulator in the future. 

Here what I want to do:

git clone https://github.com/adam-becker/psxact.git
cd psxact
mkdir build
cd build
cmake ../
make

Successfully..

Now, it doesn't have GUI for execute PSXAct.. so that mean I will have to use terminal like Command Line.. Should I put bios in PSX BIOS folder along with PSX ACT ? If so

PSXACT can be invoked via command line, using the following simple interface:

$ psxact <bios file here> <game file here>

But its command line.. Will it run with terminal for a macOS too ? Awaiting your reply, thanks.

**Comment by adam-becker** [comment]
The command line usage is (quoting the readme):

`$ psxact <bios file here> <game file here>`

In a terminal on Unix systems (which I think macOS still somewhat classifies as) you'd have to put a `./` infront of that, resulting in:

`$ ./psxact <bios file here> <game file here>`

Where the bios/game file names are the absolute paths of the files, stored anywhere on your computer. For simplicity, I place my BIOS file in the same directory as the executable. For detailed build instructions, you can have a look at what the `.travis.sh` script and `.travis.yml` config file are doing to build for OSX. It should be conceptually similar to what you'd have to do on an arbitrary macOS.

Don't expect much from PSXACT currently, I'm still working through a few bugs before commercial games can even boot.

**Comment by azoreseuropa** [comment]
Thank you.

I am aware that PSXACT's development and before commercial games can even boot. That's why I asked you about command line/terminal for macOS in the near future. Thanks again. :D

**Comment by adam-becker** [comment]
Were you able to get the program to work?

**Comment by azoreseuropa** [comment]
Hi! No, I just make a folder "psxact" and it is in download section. I put execute and bios in it :  psxact and PSX - SCPH1001 without a game for now. And test.. I got this message:

myname-MBP:build myname$ $ ./psxact PSX - SCPH1001.bin
-bash: $: command not found

**Comment by adam-becker** [comment]
You don't need to put the '$' in the command, the '$' is used as a sort of variable to represent, in your case, the following:

`myname-MBP:build myname$`

So just type in:

`./psxact "PSX - SCPH1001.bin" "any random game .bin file name here"`

**Comment by azoreseuropa** [comment]
Are you sure ? I put execute psxact into BLUE FOLDER "PSXACT" and I put bios in it along with game.bin into the BLUE FOLDER. It is in DOWNLOADS area from FINDER. Sorry about my English.

**Comment by Thunder07** [comment]
I've a feeling you're (1) not inside the right directory,(2) didn't even compile the program.

**Comment by azoreseuropa** [comment]
Can you help me out, adam-becker ? I need the right directory to tell terminal to find it.

**Comment by azoreseuropa** [comment]
@Thunder, I compile it correctly and it is 100% successfully.

adam-becker, psxact folder is in DOWNLOADS directory through Finder.

**Comment by adam-becker** [comment]
I'm not a mac expert, so I don't know what the absolute path for the `Downloads` folder is.

You can probably use `ls` and `cd` commands to find your way around, or google where the path is.

**Comment by azoreseuropa** [comment]
Yeah, you are right. You do this: Cd commands to find the directory then type: ./psxact SCPH1001.BIN game.bin and PSX BIOS boot then shut down. Thats about it. So it's working for now. :) Thank you.

**Comment by adam-becker** [comment]
No problem, closing this since everything seems to be in order.
