### ISSUE TITLE
Where you find document to coding to improve this emulator

### ISSUE THREAD

**Issue by zminhquanz** [adam-becker/psxact#20]
i will contribute to code some about opcode CPU

**Comment by adam-becker** [comment]
There are documents available online for the instruction set the CPU uses, but there are no legally released documents for the actual CPU itself, so many of the documents you can find may be misleading or counterproductive.

That being said, as far as instructions go you can find one [here](https://cgi.cse.unsw.edu.au/~cs3231/doc/R3000.pdf) see page `A-6`.

However, I have to tell you that PSXACT has a CPU that is basically fully implemented, and verified as working (including in branch delays, load delays, and branch instruction encoding) using test ROMs.

**Comment by zminhquanz** [comment]
So if you fully implement on CPU , i think to implement SPU , GTE , or writing API OpenGL , DirectX or Vulkan , if it works successful , i think it's the first PSX emulator doesn't use plugin

**Comment by zminhquanz** [comment]
@adam-becker can i you find document about GTE , SPU

**Comment by adam-becker** [comment]
@zminhquanz There are at least 3 other emulators I know of that don't use plug-ins:

- no$psx
- mednafen
- rustation

And, speaking of no$psx, that's also where you'll find the most complete [documentation of the PlayStation](http://problemkaputt.de/psx-spx.htm)
